Single hash
jazzband/pip-tools pull request #1406
Opened 2021-05-31 15:25 UTC by plannigan

**Changelog-friendly one-liner**: Option to restrict generated hashes to the single best matching file

Closes #1330 

##### Contributor checklist

- [x] Provided the tests for the changes.
- [x] Gave a clear one-line description in the PR (that the maintainers can add to CHANGELOG.md on release).
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

2021-05-31 15:44 UTC, plannigan commented
The `mypy` failures in the pre-commit.ci look like they are legitimate, but not related to my changes. I am getting the same errors when running `checkqa` locally on the default branch.

2021-06-05 11:04 UTC, plannigan commented
Pulled in the latest changes to the default branch and now `mypy` is passing. The rest of the CI is waiting for a maintainer to approve it to run.

2021-06-09 12:56 UTC, plannigan commented
I switched to the compatibility implementation of `nullcontext()` which will resolve the previous failure on python 3.6.

2021-06-22 08:04 UTC, ssbarnea approved these changes
While I do not see myself using it, it does still LGTM, especially as the number of hashes
can become quite large for some packages.

Still, I hope others will review the change better and note if there are reasons for not doing this change.

2021-06-22 08:19 UTC, atugushev commented
Can we postpone this to 6.3.0? There is no rush and i'd like to take a look at this later.

2021-06-25 12:05 UTC, plannigan commented
Pulled in master and added a test case for `single_hash` the FakeRepository. That should make CodeCov happy.

Looks like 6.2.0 was released earlier this week, so feel free to merge when you are ready.

2021-06-25 12:39 UTC, ssbarnea commented
Hint for @plannigan : to avoid waiting to workflow approval you could try to make a very small contribution first, like fixing a typo (i bet there is one to fix). Once you already contributed successfully workflow approval is no longer needed. Another option would to join https://jazzband.co/ which is automated if I remember well.

2021-06-26 14:30 UTC, atugushev reviewed
I've tried locally, but the output still has many hashes. Check this out:

```ini
# requirements.in
psycopg2
```

```console
$ pip-compile --generate-hashes --single-hash
#
# This file is autogenerated by pip-compile with python 3.8
# To update, run:
#
#    pip-compile --generate-hashes --single-hash
#
psycopg2==2.9.1 \
    --hash=sha256:079d97fc22de90da1d370c90583659a9f9a6ee4007355f5825e5f1c70dffc1fa \
    --hash=sha256:2087013c159a73e09713294a44d0c8008204d06326006b7f652bef5ace66eebb \
    --hash=sha256:2c992196719fadda59f72d44603ee1a2fdcc67de097eea38d41c7ad9ad246e62 \
    --hash=sha256:7640e1e4d72444ef012e275e7b53204d7fab341fb22bc76057ede22fe6860b25 \
    --hash=sha256:7f91312f065df517187134cce8e395ab37f5b601a42446bdc0f0d51773621854 \
    --hash=sha256:830c8e8dddab6b6716a4bf73a09910c7954a92f40cf1d1e702fb93c8a919cc56 \
    --hash=sha256:89409d369f4882c47f7ea20c42c5046879ce22c1e4ea20ef3b00a4dfc0a7f188 \
    --hash=sha256:bf35a25f1aaa8a3781195595577fcbb59934856ee46b4f252f56ad12b8043bcf \
    --hash=sha256:de5303a6f1d0a7a34b9d40e4d3bef684ccc44a49bbe3eb85e3c0bffb4a131b7c
    # via -r requirements.in
```

2021-06-28 12:40 UTC, plannigan commented
I am not able to reproduce that result (see my results below). @atugushev Can you provide some more information on your setup and how you got the above output? 

```
(.venv) C:\Users\plannigan\code\pip-tools>git log -1
commit 876fcb2a6938da53c9590f9dc7d44f1564d9d62d (HEAD -> single-hash, origin/single-hash)
Author: Patrick Lannigan <p.lannigan@gmail.com>
Date:   Fri Jun 25 07:53:50 2021 -0400

    Add test case for fake repository with single hash

(.venv) C:\Users\plannigan\code\pip-tools>git status
On branch single-hash
Your branch is up to date with 'origin/single-hash'.

nothing to commit, working tree clean

(.venv) C:\Users\plannigan\code\pip-tools>python --version
Python 3.8.6

(.venv) C:\Users\plannigan\code\pip-tools>pip list
Package    Version              Location
---------- -------------------- ------------------------------
click      8.0.1
colorama   0.4.4
pep517     0.10.0
pip        21.1.3
pip-tools  6.2.1.dev14+g876fcb2 c:\users\plannigan\code\pip-tools
setuptools 49.2.1
toml       0.10.2
wheel      0.36.2

(.venv) C:\Users\plannigan\code\pip-tools>type requirements.in
psycopg2

(.venv) C:\Users\plannigan\code\pip-tools> pip-compile --generate-hashes --single-hash
#
# This file is autogenerated by pip-compile with python 3.8
# To update, run:
#
#    pip-compile --generate-hashes --single-hash
#
psycopg2==2.9.1 \
    --hash=sha256:2c992196719fadda59f72d44603ee1a2fdcc67de097eea38d41c7ad9ad246e62
    # via -r requirements.in
```

2021-07-07 04:51 UTC, atugushev commented
It looks like there is an issue with existing hashes in `requirements.txt`. How to reproduce:

1. Generate hashes first:
```console
$ pip-compile --generate-hashes
#
# This file is autogenerated by pip-compile with python 3.8
# To update, run:
#
#    pip-compile --generate-hashes
#
psycopg2==2.9.1 \
    --hash=sha256:079d97fc22de90da1d370c90583659a9f9a6ee4007355f5825e5f1c70dffc1fa \
    --hash=sha256:2087013c159a73e09713294a44d0c8008204d06326006b7f652bef5ace66eebb \
    --hash=sha256:2c992196719fadda59f72d44603ee1a2fdcc67de097eea38d41c7ad9ad246e62 \
    --hash=sha256:7640e1e4d72444ef012e275e7b53204d7fab341fb22bc76057ede22fe6860b25 \
    --hash=sha256:7f91312f065df517187134cce8e395ab37f5b601a42446bdc0f0d51773621854 \
    --hash=sha256:830c8e8dddab6b6716a4bf73a09910c7954a92f40cf1d1e702fb93c8a919cc56 \
    --hash=sha256:89409d369f4882c47f7ea20c42c5046879ce22c1e4ea20ef3b00a4dfc0a7f188 \
    --hash=sha256:bf35a25f1aaa8a3781195595577fcbb59934856ee46b4f252f56ad12b8043bcf \
    --hash=sha256:de5303a6f1d0a7a34b9d40e4d3bef684ccc44a49bbe3eb85e3c0bffb4a131b7c
    # via -r requirements.in
```

2. Then run `pip-compile` again with the single hash option:
```console
$ pip-compile --generate-hashes --single-hash
#
# This file is autogenerated by pip-compile with python 3.8
# To update, run:
#
#    pip-compile --generate-hashes --single-hash
#
psycopg2==2.9.1 \
    --hash=sha256:079d97fc22de90da1d370c90583659a9f9a6ee4007355f5825e5f1c70dffc1fa \
    --hash=sha256:2087013c159a73e09713294a44d0c8008204d06326006b7f652bef5ace66eebb \
    --hash=sha256:2c992196719fadda59f72d44603ee1a2fdcc67de097eea38d41c7ad9ad246e62 \
    --hash=sha256:7640e1e4d72444ef012e275e7b53204d7fab341fb22bc76057ede22fe6860b25 \
    --hash=sha256:7f91312f065df517187134cce8e395ab37f5b601a42446bdc0f0d51773621854 \
    --hash=sha256:830c8e8dddab6b6716a4bf73a09910c7954a92f40cf1d1e702fb93c8a919cc56 \
    --hash=sha256:89409d369f4882c47f7ea20c42c5046879ce22c1e4ea20ef3b00a4dfc0a7f188 \
    --hash=sha256:bf35a25f1aaa8a3781195595577fcbb59934856ee46b4f252f56ad12b8043bcf \
    --hash=sha256:de5303a6f1d0a7a34b9d40e4d3bef684ccc44a49bbe3eb85e3c0bffb4a131b7c
    # via -r requirements.in
```

---

Note that `--no-reuse-hashes` helps to generate single hash output:
```console
$ pip-compile --generate-hashes --no-reuse-hashes --single-hash
#
# This file is autogenerated by pip-compile with python 3.8
# To update, run:
#
#    pip-compile --generate-hashes --no-reuse-hashes --single-hash
#
psycopg2==2.9.1 \
    --hash=sha256:de5303a6f1d0a7a34b9d40e4d3bef684ccc44a49bbe3eb85e3c0bffb4a131b7c
    # via -r requirements.in
```

2021-07-07 15:25 UTC, plannigan commented
Ok, that makes sense. The local repository checks the cache before calling `get_hashes()` for the PyPI repository. I'll have some time to circle back on this in a few days.

2021-07-11 10:25 UTC, plannigan commented
Thanks for tracking down the hash reuse issue. The fix was a simple check to see if there were more than one existing hash.

2021-10-01 17:54 UTC, AndydeCleyre requested changes
Small English changes in the readme, please:

- "give" to "given"
- "match" to "matching"

Thanks!

2021-10-01 18:18 UTC, AndydeCleyre commented on piptools/repositories/base.py
> +        False (the default), included hashes for all of the files for a given requirement.
Small typo: please change "included" to "include"

2021-10-04 04:29 UTC, AndydeCleyre commented on piptools/repositories/pypi.py
> +        False (the default), included hashes for all of the files for a given requirement.
Please change this one, too: "included" to "include" or "includes"

2021-10-04 13:17 UTC, plannigan commented
Fixed the grammar in a few more locations in docstrings. Should be good to go now.

2022-12-14 07:13 UTC, ssbarnea commented
Closing this PR as it seems outdated. Please try to reopen it once these problems are sorted. Small PRs that are easy to review are likely to be merged quickly as they impose less risks.

2022-12-14 07:13 UTC, closed without merging