Fix changelog category title template
jazzband/pip-tools pull request #1424
Opened 2021-06-21 06:01 UTC by atugushev

To be consistent with the current template in changelog and release page.

2021-06-21 08:11 UTC, ssbarnea approved these changes

2021-06-21 08:14 UTC, ssbarnea requested changes
The extra space at the end looks like a bug to me, we will likely endup with extra spacing that is not needed.

2021-06-21 08:16 UTC, atugushev commented on .github/release-drafter.yml
> +category-template: "$TITLE: "
```suggestion
category-template: "$TITLE:"
```

@ssbarnea that's a bug. Thanks for noticing.

2021-06-22 07:56 UTC, ssbarnea approved these changes

2021-06-22 07:56 UTC, merged