Add changelog to the Sphinx docs
jazzband/pip-tools pull request #1469
Opened 2021-08-12 21:20 UTC by webknjaz

##### Contributor checklist

- [x] Provided the tests for the changes.
- [x] Assure PR title is short, clear, and good to be included in the user-oriented changelog
- [x] Assure one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

2021-08-20 14:45 UTC, jdufresne commented
IMO, we'd be better off converting the top-level document to rst and then moving it into the docs directory. It would then become a first class document in the docs infrastructure.

2021-08-20 14:52 UTC, ssbarnea commented
@jdufresne I find markdown more contributor friendly than ReST, especially for less experienced python developers. As sphinx already got decent md support I see a migrations towards md everywhere as better in long term.

I personally can write both, but I based on what I seend as incoming pull requests from others, people struggle less writing markdown than rst.

2021-08-20 15:00 UTC, jdufresne commented
> As sphinx already got decent md support I see a migrations towards md everywhere as better in long term.

I still prefer rst, but am not against switching to md.

Either way, this sounds like an orthogonal issue to me. First step would be moving the changelog into the official docs in whatever format they are currently being written in.

2021-08-20 15:52 UTC, webknjaz commented
I also prefer RST but it's out of the scope here. Plus it's probably hard with the current integration that relies on GH PRs, hence MD.

2021-08-20 16:01 UTC, jdufresne requested changes
@webknjaz I'm not clear on your position, can you clarify?

Are you saying moving the changelog to the `docs/` directory as rst is out of scope? If so, I disagree. If we're going to better integrate the changelog then I think we should do so completely by moving it fully to the docs.

> Plus it's probably hard with the current integration that relies on GH PRs, hence MD.

Can you be explicit what this means? I don't know what you're referring to.

We can always rework or reevaluate tools if they are making other work more difficult.

2021-08-20 16:06 UTC, webknjaz commented
It's out of the scope of *this PR*. Because it's about including one file into the sphinx setup and *nothing else*.

Fully remaking the changelog generation procedure is something that does not fit within the scope.

2021-08-31 12:00 UTC, webknjaz commented
(rebased after merging #1480)

2021-08-31 13:13 UTC, ssbarnea approved these changes

2021-08-31 13:13 UTC, merged