Feature/linesep slim
jazzband/pip-tools pull request #1584
Opened 2022-02-16 05:51 UTC by AndydeCleyre

##### Contributor checklist

- [ ] Provided the tests for the changes.
- [ ] Assure PR title is short, clear, and good to be included in the user-oriented changelog

##### Maintainer checklist

- [ ] Assure one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

2022-07-18 17:20 UTC, graingert commented
I'm a -1 on this because I'm only impacted by pip-compile producing incorrect line separators when it's run misconfigured. Eg the user forgot to run my shim wrapper or apply pre-commit

2022-07-18 21:06 UTC, graingert commented
> > I'm a -1 on this because I'm only impacted by pip-compile producing incorrect line separators when it's run misconfigured. Eg the user forgot to run my shim wrapper that emits normal newlines or apply pre-commit
> 
> This doesn't address that problem?

Ah right, I see it, the code still defaults to adopt the existing linesep if possible

2022-07-18 21:26 UTC, AndydeCleyre commented on piptools/scripts/compile.py
> +    "--force-unix-newlines",
I'm going to push here an update based on changes in the other PR. What do you think the flag could be called instead?

2022-07-18 21:36 UTC, graingert requested changes

2022-07-18 21:40 UTC, AndydeCleyre commented on piptools/scripts/compile.py
> +    "--force-unix-newlines",
`newline-is-lf` sounds descriptive, but we're being prescriptive. What about:

- `write-lf`
- `force-lf`
- `write-lf-newlines`
- `force-lf-newlines`

?

2022-07-18 21:51 UTC, AndydeCleyre commented
@ssbarnea I understand you don't really want this in any form, but if it does happen in this (single flag) form, would you like to suggest a better flag name?

2022-10-06 09:15 UTC, ssbarnea commented
I think that this change was obsoleted by #1652 so closing. If not, please rebase and reopen.

2022-10-06 09:15 UTC, closed without merging