Removed strange (updating-requirements)= from README.md
jazzband/pip-tools pull request #2084
Opened 2024-05-03 10:58 UTC by denisSurkov

Removed strange `(updating-requirements)=`

##### Contributor checklist

- [x] Included tests for the changes.
- [x] PR title is short, clear, and ready to be included in the user-facing changelog.

##### Maintainer checklist

- [ ] Verified one of these labels is present: `backwards incompatible`, `feature`, `enhancement`, `deprecation`, `bug`, `dependency`, `docs` or `skip-changelog` as they determine changelog listing.
- [ ] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

2024-05-04 20:50 UTC, webknjaz requested changes
It's MyST, it should be there.

2024-05-06 11:54 UTC, WhyNotHugo commented
It doesn't look like the README is rendered with `MyST`. The string `(updating-requirements)=` is just rendered as a regular paragraph on GitHub.

2024-05-06 14:06 UTC, webknjaz commented
Yep. GitHub uses its own flavor — GFM. But this document is also used in Sphinx. GH is known for breaking rendering, though (they recently broke RST even more than before..). So I don't really care about this. I think it's better to have nicer docs on RTD where we have full control over the markup. That includes the changelog (which is currently isn't even displayed there, I think).

One way to solve this would be to remove most of the README and link the Sphinx docs but that would remove the ability to see so much content on the GH repo front page.

2024-05-06 14:09 UTC, denisSurkov commented
Well, that's true. @webknjaz , sorry I didn't check it beforehand. I'll close PR.

https://pip-tools.readthedocs.io/en/stable/#updating-requirements

![no strange string in docs](https://github.com/jazzband/pip-tools/assets/34986204/4d3942f7-aaa0-4a89-ba97-c8118ba4ee25)

2024-05-06 14:09 UTC, closed without merging

2024-05-06 14:24 UTC, webknjaz commented
FTR this is something to be discussed, clearly. And if someone would like to offer different opinions and implementation suggestions, I won't be in a way. Of course, it'll mean taking on more maintenance responsibility in this specific area of the project.
I just wanted to document why things are as they are today so that it could be taken into account in the future. Not many people were involved in plugging in Sphinx and then MyST so it may not be obvious to an average contributor.

2024-05-06 15:21 UTC, WhyNotHugo commented
I wasn't aware the sphinx was including the README. Thanks for your clarity.